### ISSUE TITLE
Quit methods for JVM unclear

### ISSUE THREAD

**Issue by max3-2** [John-Hennig/MPh#10]
Hi,

first of all thanks for the great work. Can you elaborate on why you use your exit code instead if shutdownJVM()?

Background: Running 
```
logger.info('Shutting down the Java virtual machine.')
jpype.java.lang.Runtime.getRuntime().exit(0)
logger.info('Java virtual machine has shut down.')
```
wont log the second part since my interpreter closes down at ...exit() with the JVM. This leads to some problems with pyqt, I try to build an UI around the package...

I tested using `jpype.shutdownJVM()` and found the following: Connecting a client to a server and / or running a server will allow subsequent shutdown with the above (or for that matter, just exiting the interpreter). As soon as COMSOL was active, e.g. loading or simply creating a model, it will block `shutdownJVM()` running indefinitely.

**Comment by John-Hennig** [comment]
Yes, I've noticed the same behavior, which is why `.exit()` is called. See issue #1 as well as the script `test_shutdown` in the [`sandbox`](https://github.com/John-Hennig/MPh/tree/master/sandbox) folder, which tests exactly that and has more details.

Also true, the very last line of code is never reached. I would much prefer to just call `jpype.shutdownJVM()`, but it does not work reliably. In fact, more often than not it doesn't work. It seems to me, now, that this isn't a problem with JPype, but rather a design flaw of the Comsol client, as the Comsol documentation insists on calling `System.exit(0)` even in Java code. I have no idea why that would be necessary, but that's the way it is.

I have built PyQt applications based on MPh myself, where Comsol would be running inside a `QThread`. I have never had an issue with this brute-force shutdown as it's only ever called at the every end of the Python session.

**Comment by max3-2** [comment]
(Nevermind?), I found #1 

To add to that, with `jpype==1.2.1` and running `macOS`, `Comsol 5.5`, the block seems indefinitely (> 5 min). 

Interestingly, the java process which is invoked disappears right at the function call. However the lock is not getting released

**Comment by max3-2** [comment]
Oh and BTW: Can you pinpoint me to where the documentation states the `System.exit(0)`? I do have an account with support at COMSOL - this might open up some possibilities.

**Comment by John-Hennig** [comment]
Sure, it's at the bottom of page 23 in the [Programming Reference Manual of Comsol 5.6](https://www.comsol.com/documentation/5.6/COMSOL_ProgrammingReferenceManual.pdf).

> You also need to call `System.exit(0)` at the end of the Java program to terminate the process.

**Comment by John-Hennig** [comment]
On second read, maybe that sentence does not apply to stand-alone clients, but only to client-server mode.

By the way, since you seem to be on macOS, would be great if you could comment on issue #9 as to what extent things work there. Also, after re-reading the page linked above, I've noticed that the docs have somewhat changed between Comsol 5.5 and 5.6. I just pushed a commit related to that. So that's currently only in `master`, not in the latest release 0.8.0, though I don't think there'd be any difference in behavior.

**Comment by max3-2** [comment]
See issues. I'll reach out to COMSOL - maybe they have an idea...

**Comment by John-Hennig** [comment]
Okay, great.

Also, as I've learned from your PR, you seem to be using the Spyder IDE. In my experience, using Spyder when developing PyQt applications is not a good fit since Spyder is itself a PyQt application, so sometimes gets in the way of things working as intended. You should check if the above issue persists if you run the app outside of the Spyder console.

**Comment by max3-2** [comment]
Thanks for the hint. Just used spyder for quick coding, usually not the case. Still I thought it might be quite popular by now so added it to gitignore.
