### ISSUE TITLE
Locating Comsol installation fails

### ISSUE THREAD

**Issue by stevenaroberts89** [John-Hennig/MPh#2]
I may have missed something in the installation. When I run the program its not able to find my client, which is installed at C:\Program Files\COMSOL\COMSOL50\Multiphysics\COMSOL Launchers

   
    import mph
    client = mph.Client(cores=1, version = '5.0')

Could not locate any Comsol installation.

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-10-11fa5b9b9e00> in <module>
----> 1 client = mph.Client(cores=1, version = '5.0')

C:\Anaconda\envs\COMSOL\lib\site-packages\mph\client.py in __init__(self, cores, version, port, host)
     83 
     84         # Determine relevant folders of the Comsol back-end.
---> 85         main = backend.folder(version)
     86         arch = backend.architecture()
     87         jre  = main / 'java' / arch / 'jre' / 'bin'

C:\Anaconda\envs\COMSOL\lib\site-packages\mph\backend.py in folder(version)
    206     """
    207     if version is not None:
--> 208         if version not in versions():
    209             error = f'Version {version} is not installed.'
    210             logger.error(error)

C:\Anaconda\envs\COMSOL\lib\site-packages\mph\backend.py in versions()
    184         error = 'Could not locate any Comsol installation.'
    185         logger.error(error)
--> 186         raise RuntimeError(error)
    187 
    188     # Sort versions by name.

RuntimeError: Could not locate any Comsol installation.

**Comment by John-Hennig** [comment]
First of all. you haven't missed anything. It's intended to work just like that. You wouldn't even have to specify the version explicitly (`version = '5.0' in your code), but that's not the issue.

However, the Comsol version you're using, 5.0, is quite old, released at the end of 2014. The oldest version I've ever tested with is 5.3a, from 2017. There's a chance that changes have been made to the install locations. I don't know. I don't have the 5.0 documentation anymore. Nor do I have the installer DVD from back then.

So I don't know if I can get to the bottom of this. What you could do though, is download the source code (grab the zip archive here and unpack it), run `python test_backend.py log` in the `tests` folder, and post the log messages it outputs to the console. That might provide some clues as to why the Comsol client isn't where MPh expects it to be.

What MPh does is: It retrieves the installation folder from the Windows Registry and then checks that `comsolmphserver.exe` is in fact inside that directory. I seem to remember that the server executable was, at some point in the past, just called `comsolserver.exe` (without `mph` in the name), so that *might* be the issue. Maybe.

**Comment by stevenaroberts89** [comment]
Thanks for the quick response! I have 5.4 on our main computer but was trying it on a spare. I'll try both suggestions.
