### ISSUE TITLE
Evaluation of electric field

### ISSUE THREAD

**Issue by Joel-H-dot** [John-Hennig/MPh#35]
I'm trying to evaluate an electric field at some pre-defined points, is there anyway to do this currently? The MATLAB version of what I want is [Et_x,Et_y,Et_z] = mphinterp(model,{'mf.Ex','mf.Ey','mf.Ez'},'coord',eval_points','Complexout','on');

I tried using something similar to (x, y, z, E) = model.evaluate(['x', 'y', 'z', 'mf.Ex']) as in the documentation and then evaluating the arrays 'x', 'y' and 'z' to find the corresponding field, but am receiving a few errors: 

(x, y, z, E) = model.evaluate(['x', 'y', 'z', 'mf.Ex'])
ValueError: too many values to unpack (expected 4)

I got rid of the 'z' evaluation, which solves this particular error, but then how to get 3-D data? 
________________________________________________________________________
The next problem is an issue with extracting complex field data, specifically the code segment in model

            if eval.isComplex():
                results += 1j * array(eval.getImagData())
                self.java.result().numerical().remove(etag)
                logger.info('Finished global evaluation.')

Which produces the error 

 results += 1j * array(eval.getImagData())
ValueError: non-broadcastable output operand with shape () doesn't match the broadcast shape 

I saved the imaginary data to an excel file and found that it was extracting ~60000 different datasets for 10 different frequencies for a domain probe. There should only be one dataset. There was also an exception raised:

numpy.core._exceptions.UFuncTypeError: Cannot cast ufunc 'add' output from dtype('complex128') to dtype('int32') with casting rule 'same_kind'

![image](https://user-images.githubusercontent.com/60707891/114398027-38c91000-9b97-11eb-91de-196f51ec0d54.png)

I replaced the above code with the following, which fixed the issue, but is a bit of a bodge job, but did solve the problem of the different datatypes and of extracting a single dataset per frequency. 

            if eval.isComplex():
                D = array(eval.getReal())+1j * array(eval.getImag())
                results = numpy.zeros((1,len(D[0,:])),dtype=numpy.complex_)
                results[0,:]=D[0,:]

Any idea on why so many different datasets are extracted for a domain probe? 

all the best,

Joel.

**Comment by John-Hennig** [comment]
Hi Joel, thanks for sharing and starting a discussion on this.

First of all, let me say that [`evaluate()`](https://mph.readthedocs.io/en/stable/api/mph.Model.html#mph.Model.evaluate) is certainly limited in what it can do. Some limitations are mentioned in the linked API documentation. Most of them are not. Simply because I don't know what they are and don't have the time to find out. It covers *my* use cases, that I know. But that's a small subset of what Comsol offers: The "Results" chapter in the [Comsol API documentation](https://www.comsol.com/documentation/5.6/COMSOL_ProgrammingReferenceManual.pdf) is almost 350 pages long.

You have access to all of these features directly in your code. Just replace every occurrence of `model` in the Comsol docs with `model.java`, if `model` is what you named the Python [`Model`](https://mph.readthedocs.io/en/stable/api/mph.Model.html#mph.Model) object.

You fixed your issue with the complex field data basically by calling `eval.getImagData()` instead of `eval.getImag()` in the library code. That may be correct, but `.getImagData()` isn't even documented for the `Eval` feature (page 633). As opposed to `EvalPoint` (page 644) for example, which does have `.getImag()`. If this is proven to work, I could change that in the library. But I don't want to base that on just one example.

If you want to help plugging the holes in `evaluate()`, please do. Basically what we need here are simple models (minimal examples of a general use case) where there's a clear expectation as to the returned output. Then I can make it part of the test suite and it can go into the library. But, obviously, it's not easy to come up with such examples, that takes time. And is probably why the Comsol API has all these different ways to do one thing.

As for the other issue… Evaluation of electric fields should definitely work. This
```
(x, y, z, E) = model.evaluate(['x', 'y', 'z', 'mf.Ex'])
ValueError: too many values to unpack (expected 4)
```
certainly works for stationary solutions in a 3d geometry, I've tested (used) that extensively. So you're saying you got back 3 values instead of 4 when you included `z`? (The `ValueError` is raised during tuple unpacking of the returned value, i.e. not inside MPh.) What happens when you evaluate `z` alone? Anyway, I have no idea how to reproduce that and have never seen that happen before.

As for the Matlab function `mphinterp`… The Comsol API has an `Interp` feature (page 688), which may do similar things. But as far as I remember (it's been a while since I last used Matlab for this), the Matlab function adds some extra functionality. Like maybe the `'coord', 'eval_points'` arguments that you want to use. In principle we could add a new method like `.interpolate()` to the `Model` class and expose that feature. But, again, that's a lot of work, especially in terms of testing.

**Comment by Joel-H-dot** [comment]
Hi John, thanks for the detailed response. I will take some time to digest the document you've linked. 

I'm not sure myself why I can't extract the co-ordinate data, I've just tried to extract the 'x' and 'y' and it raises the same exception, so it's for all the co-ordinate data. I'm using a frequency domain study, that may have something to do with the difference, but I doubt it. 

I will have  play around with the COMSOL API and model function, if I manage to clear up the errors I will share it here. 

Finally, thanks for starting this project, it has been on my mind for some time switching from MATLAB livelink to python, I imagine it will be useful to many people. 

Joel.

**Comment by Joel-H-dot** [comment]
Hi all, 

I have solved the issue of extracting the field data, I am not sure why the evaluate function failed for my case, but I found an alternative. If you dig into the model function written here you can use the following instead
        etag = self.java.result().numerical().uniquetag('eval')
        eval = self.java.result().numerical().create(etag, 'Interp')
with 'Interp' you can use the following 
        if coord is not None:
            eval.set('coord', coord)
you can then pass co-ordinates into the evaluate function to return corresponding field values.

**Comment by John-Hennig** [comment]
Ah, okay, good to know. So "evaluate" doesn't work, but "interpolate" does. I still don't get why `evaluate()` has a problem with the basic coordinates in your model. Then again, I don't remember ever using a frequency sweep, so I'm certainly missing something there. But this makes a case for adding `interpolate()` to the API. Thanks!

**Comment by Joel-H-dot** [comment]
Hi John, 

Neither do I, it's mystified me all day! Cheers for your help, made finding a solution much easier. 

Joel.
