### ISSUE TITLE
winreg module is missing in linux 

### ISSUE THREAD

**Issue by ebrahimnorouzi** [John-Hennig/MPh#6]
I have a python 3.6.12 installed in linux and when I import mph in python, I get this error.
ModuleNotFoundError: No module named 'winreg'

**Comment by John-Hennig** [comment]
Linux, or any operating system other than Windows, is currently not supported by MPh. See [chapter "Limitations" in the documentation](https://mph.readthedocs.io/en/latest/limitations.html).

**Comment by ebrahimnorouzi** [comment]
Exactly, I found a solution for that and its fake winreg library in python.

Best regards,
Ebrahim

On Jan 11, 2021, at 5:14 PM, John Hennig <notifications@github.com> wrote:

﻿

Linux, or any operating system other than Windows, is currently not supported by MPh. See chapter "Limitations" in the documentation<https://mph.readthedocs.io/en/latest/limitations.html>.

**Comment by ebrahimnorouzi** [comment]
Exactly, I found a solution for that and its fake winreg library in python.

Best regards,
Ebrahim

-- 
Ebrahim Norouzi
M.Sc. Materials Science and Simulation
Interdisciplinary Center for Advanced Materials Simulation (ICAMS)
Ruhr-University Bochum
44780 Bochum
Germany
Tel. +49 157 87 975458
Email ebrahim.norouzi@rub.de

**Comment by John-Hennig** [comment]
Hello Ebrahim,

It's not enough to "fake" the WinReg library. The only reason it is loaded is to locate the Comsol installation, based on the information the Comsol installer has left in the Windows Registry. This only helps on Windows though. On Linux, you will find that you cannot start the Comsol client, even if you "successfully" loaded MPh.

On Linux, that mechanism (to locate the Comsol installation and start the "client") has to be replaced by something else instead. WinReg would not even be loaded then. See [this pull request](https://github.com/John-Hennig/MPh/pull/3/commits) (contributed by Jacob Feder) — especially the diff on the first commit, where `import`ing `winreg` is skipped in case the `import` fails.

To elaborate a little further, that pull request only covers client–server connections on Linux, i.e., the use case where you would start an independent Comsol server and then, in a different Python session, a client that connects to that very server.

In an effort to achieve full Linux compatibility, I've been trying to get <i>stand-alone</i> Comsol clients to work. Then one could script Comsol in a single Python session and would not have to worry about the server instance. After all, that's the most common use case — at least as far as I'm concerned. However, I still haven't quite figured that out yet. Though I have uploaded a test script, [`test_client`](https://github.com/John-Hennig/MPh/blob/master/sandbox/test_client.py), to demonstrate the (unresolved) issue with that.

Best,
John

**Comment by ebrahimnorouzi** [comment]
Hi John,

Thank you for your explanation. That is helpful. I have one question. Is it possible to do more things in python, for instance create a model or geometry, something like complete power of java? What are the difficulties?

I am materials scientists and really need that for my project but do not know about the possibility of developing python api for comsol. Do you have any references and suggestions for me?

Best regards,
Ebrahim

-- 
Ebrahim Norouzi
M.Sc. Materials Science and Simulation
Interdisciplinary Center for Advanced Materials Simulation (ICAMS)
Ruhr-University Bochum
44780 Bochum
Germany
Tel. +49 157 87 975458
Email ebrahim.norouzi@rub.de

**Comment by John-Hennig** [comment]
Short answer: yes.

All of these things — "create a model or geometry, something like complete power of java" — are possible. Not so much because of MPh itself, but rather because of JPype — the Python-to-Java bridge that MPh is built on. (All credit to [Thrameos](https://github.com/Thrameos) and the other contributors to [JPype](https://github.com/Thrameos/jpype).)

I did mention that in the documentation, if only in passing. It is not the primary focus of MPh to do these things. The primary focus is: Take an *existing* model (i.e., *not* create it in code, but rather set it up in the Comsol GUI) and then solve it. Usually, after changing parameter values and/or to implement some customized, Python-power post-processing. (Otherwise you might just click `solve` on the appropriate study node in the Comsol GUI.)

But, nevertheless, it is possible to do all of these things in code. Take this Comsol blog entry as an example: [Automate Your Modeling Tasks with the COMSOL API for use with Java®](https://www.comsol.com/blogs/automate-modeling-tasks-comsol-api-use-java/). It starts with this Java code example:
```java
import com.comsol.model.*; 
import com.comsol.model.util.*;

public class HelloWorld {

   public static void main(String[] args) {
      run(); 
   }
   public static Model run() {
      Model model = ModelUtil.create("Model"); 
      model.modelNode().create("comp1"); 
      model.geom().create("geom1", 3); 
      model.geom("geom1").feature().create("blk1", "Block"); 
      model.geom("geom1").feature("blk1").set("size", new String[]{"0.1", "0.2", "0.5"});
      model.geom("geom1").run("fin");
      return model; 
   } 
}
```

What it does is, it creates a model, which contains a 3d geometry component, which is just a block that is 0.1 by 0.2 by 0.5 meters in size.

You can do the same thing using MPh. Again, that's not the primary purpose, but it works. So in Python, with only MPh (and Comsol) installed, you would do this:
```python
import mph

client = mph.Client()
pymodel = client.create('model')
model = pymodel.java

model.modelNode().create("comp1"); 
model.geom().create("geom1", 3); 
model.geom("geom1").feature().create("blk1", "Block"); 
model.geom("geom1").feature("blk1").set("size", ["0.1", "0.2", "0.5"]);
model.geom("geom1").run("fin");
```

Note how I copy-and-pasted most of the (functional) Java code — even the semicolons, which Python simply ignores. I had to replace `new String[]{"0.1", "0.2", "0.5"}`. That's because Python does not know what `new` means. But there, Java expects a list of three strings. So I replaced that with `["0.1", "0.2", "0.5"]` — which is the Python equivalent of just that: a list of these three strings.

Occasionally, when translating Java (or Matlab) code you find in the documentation — or a blog entry, as was the case here —, you will have to amend code lines such as the one above. But they are few and far between. And the error message you'd receive should at least point you in the right direction.

The upside is:
* You don't really need to know Java. I know embarrassingly little. A bit more than what it takes to fix the code example above, but not much more.
* You don't need to install Java. It just ships with Comsol. You also don't need to worry about "compiling" Java source code to Java "classes" (via `comsolcompile`).
* You can use Python "introspection" to understand how Comsol models are "created in code". This may be the most productive feature. The Comsol documentation explains a lot of things, but not every little thing. I used the `mph.inspect()` function a lot in development.

Finally, to save the model created in the above example, we can just do this in Python:
```python
pymodel.save('model')
```

This stored a file named `model.mph` in the working directory, which you can then open in the Comsol GUI. Or use in any other (Python/Java/Matlab) script, as you please.

**Comment by ebrahimnorouzi** [comment]
Thank you for your nice suggestions.
I run mph in Linux and want to further develop the model as you said but faced one error:

pymodel = client.create('model')
Traceback (most recent call last):
  File "SourceFile", line 90, in com.comsol.model.util.ModelUtil.createUnique
  File "SourceFile", line 83, in com.comsol.model.util.ModelUtil.create
  File "SourceFile", line 42, in com.comsol.model.util.ServerModelUtil.create
  File "SourceFile", line 636, in com.comsol.nativeutil.d.b.l
  File "SourceFile", line 22, in com.comsol.nativeutil.d.c.<clinit>
  File "SourceFile", line 157, in com.comsol.nativejni.util.FlLicense.getInstance
  File "SourceFile", line 71, in com.comsol.nativejni.util.FlLicense.<init>
  File "SourceFile", line -2, in com.comsol.nativejni.util.FlLicense.initWS0
Exception: Java Exception

The above exception was the direct cause of the following exception:

pymodel = client.create('model')
Traceback (most recent call last):
  File "SourceFile", line 90, in com.comsol.model.util.ModelUtil.createUnique
  File "SourceFile", line 83, in com.comsol.model.util.ModelUtil.create
  File "SourceFile", line 42, in com.comsol.model.util.ServerModelUtil.create
  File "SourceFile", line 636, in com.comsol.nativeutil.d.b.l
  File "SourceFile", line 22, in com.comsol.nativeutil.d.c.<clinit>
  File "SourceFile", line 157, in com.comsol.nativejni.util.FlLicense.getInstance
  File "SourceFile", line 71, in com.comsol.nativejni.util.FlLicense.<init>
  File "SourceFile", line -2, in com.comsol.nativejni.util.FlLicense.initWS0
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/IWM/runs/pydev/py36-venv/lib64/python3.6/site-packages/mph/client.py", line 183, in create
    java = self.java.createUnique('model')
mph.client.UnsatisfiedLinkError: java.lang.UnsatisfiedLinkError: com.comsol.nativejni.util.FlLicense.initWS0(Lcom/comsol/nativejni/CPointer;)V

I also have the same error by loading the .mph file. How should I use mph.inspect() to get a clue about this kind of error?

**Comment by John-Hennig** [comment]
As expected. This is why Linux is not supported. I haven't quite figured out why this happens. It's something to do with the external shared libraries that aren't correctly loaded. See my earlier comment and the test script that I mentioned. The doc-string at the top of the test script also hints at a possible work-around. Though, again, I will not claim Linux support until this issue is resolved in a robust way, which it currently isn't. Unfortunately.

**Comment by ebrahimnorouzi** [comment]
I asked a user that has windows to test this for me and when the line "java.initStandalone(False)" is commented out, the exact error appears as I mentioned in my previous comment. I thought this may give some hints. But I tried many options like using graphic standalone and they are not working. 

Also using server connection is not working with this command: "java.connect('localhost', port=2036)".

**Comment by ebrahimnorouzi** [comment]
So the solution is to add server before adding client.

import mph
server = mph.Server(cores=1)
print(f'Server listing on port {server.port}.')

client = mph.Client(cores=1, port = 2036)
pymodel = client.create('model')
model = pymodel.java

and so on ...

**Comment by ebrahimnorouzi** [comment]
Sorry, I just confused about converting codes from python to java. For instance for this java code:

public class Hello_world {
  public static Model run1() {
  }
  public static Model run2(Model model) {
  }
  public static void main(String[] args) {
    Model model = run1();
    run2(model);
  }
}

Is this a proper python code? 
Is it possible to name Hello_world, run, run2 in python for better interpretation?
Where do we have to define "model = run()" an "run2(model)"?

pymodel_1 = client.create('model_run1')
model_1 = pymodel_1.java

pymodel_2 = client.create('model_run2')
model_2 = pymodel_2.java

**Comment by John-Hennig** [comment]
I guess this is Java code that was originally auto-generated by Comsol and then edited down? I don't know why Comsol's code generator splits up the `run()` method. (Note how all the code acts on the same model object, not two different ones.) But it's not necessary to do that, not even in Java. This could all be one method, even just `main()`.

In Python, you don't need any methods/functions. Not even the class definition, which is mandatory in Java. So I would omit all of that, unless there is a good reason to structure the code. I would create the model once, same way as in the earlier example, and then copy all the "functional" lines of Java code, from whichever of those methods. By "functional" I mean lines of code that modify the model object, i.e. create or change features — geometry, mesh, physics, solver, plots, exports, etc.

**Comment by John-Hennig** [comment]
Support for Linux was added in version 0.8.0, released today. See the updated [documentation](https://mph.readthedocs.io/en/latest/limitations.html) as well as issue #8. The `winreg` module is thus no longer imported unconditionally, only on Windows.
