### ISSUE TITLE
Modifying create function from Client.py to add more model features

### ISSUE THREAD

**Issue by edword12312** [John-Hennig/MPh#7]
I saw it in the comment section of def load() in Client.py that we are able to add model features intended for Java. Is there an example of how we can implement java code in here? For example, is there a way to create new geometries and add dimensions? I read the comments in the def load() function, but still have trouble understanding how I can do this?

**Comment by John-Hennig** [comment]
You already closed this issue before I even saw it. Maybe(?) because… I addressed this in the preceding issue, #6. Also, you were probably referring to the documentation of the [`create` method from the `Client` class](https://mph.readthedocs.io/en/latest/api/mph.Client.html#mph.Client.create) — rather than [`load`](https://mph.readthedocs.io/en/latest/api/mph.Client.html#mph.Client.load). Both of these — the other issue and the API documentation — should answer the question here to some extent.

Though, to reiterate, while this is not what MPh is for, it does work nevertheless: Thanks to the Python-to-Java transparency layer provided by [JPype](https://github.com/jpype-project/jpype). In terms of code examples, the best reference is the Comsol documentation itself — once you realize that the syntax in Python is virtually identical to what it is in Java (or even Matlab), give or take a few straightforward changes.

**Comment by Thrameos** [comment]
@John-Hennig if there are significantly different needs for the Java object to use the Python API, you can add a class customizer which can add Python functions above those things represented in the native Java interface.   We use this natively in JPype to do things like make a Java Iterable look like a Python sequence.  Looking at the examples, I don't think that is likely to be necessary, but I wanted to make sure you were aware of the option to customize a class to give a better interface to your users.

**Comment by John-Hennig** [comment]
As of version 0.9 this is documented in more detail. Refer to section ["Creating models: Java style"](https://mph.readthedocs.io/en/1.0/demonstrations.html#creating-models-java-style) in the latest documentation.
